# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - app-mywebapp-test-001

on:
  push:
    branches:
      - master

defaults:
  run:
    working-directory: ./src/MyWebApp

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.102'

    - name: Restore
      run: dotnet restore

    - name: Build with dotnet
      run: dotnet build --configuration Release --no-restore
    
    - name: Test 
      run: dotnet test --no-restore --verbosity normal

    - name: dotnet publish
      run: dotnet publish -c Release -o ./MyWebApp

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'app-mywebapp-test-001'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_42c6691894a647e1b9a7a2a7392d7b9f }}
        package: ${{env.DOTNET_ROOT}}/MyWebApp 
