name: Docker Pipeline - CI/CD 

on:
  workflow_run:
    workflows: ["Pipeline - CI/CD"]
    branches: [master]
    types: 
      - completed

defaults:
  run:
    working-directory: ./src/MyWebApp

jobs:
  registry:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
          
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD  }}
        login-server: ${{ secrets.DOCKER_CONTAINER_REGISTRY }}
          
    - name: Build Docker image and Push to Container Registry - Test
      run: |
        docker build . --file Dockerfile --tag ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/mywebapp-test:latest
        docker tag ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/mywebapp-test:latest ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/mywebapp-test:$(date +%s)
        docker push ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/mywebapp-test
        
    - name: Build Docker image and Push to Container Registry - Prod
      run: |
        docker build . --file Dockerfile --tag ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/mywebapp-prod:latest
        docker tag ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/mywebapp-prod:latest ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/mywebapp-prod:$(date +%s)
        docker push ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/mywebapp-prod
        
